import type { NextPage } from "next";
import Head from "next/head";
import Header from "./components/Header";
import Footer from "./components/Footer";
import styled from "styled-components";

const Wrapper = styled.div`
  width: 100vw;
  height: 100vh;
  background-color: #a29bfe;
`;

const Wrap = styled.div`
  max-width: 720px;
  min-width: 360px;
  width: 100%;
  height: 100%;
  margin: 0 auto;
  display: flex;
  flex-direction: column;
  justify-content: space-between;
`;

const Home: NextPage = () => {
  return (
    <Wrapper>
      <Wrap>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Header />

        {/* content */}

        <Footer />
      </Wrap>
    </Wrapper>
  );
};

export default Home;
